# Generated by Django 4.2.11 on 2024-04-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(choices=[('House', 'House'), ('Dance', 'Dance'), ('Trance', 'Trance'), ('Rock', 'Rock'), ('Pop', 'Pop')], default=None, max_length=10),
        ),
    ]
