# Generated by Django 4.2.11 on 2024-04-12 11:34

import SkylarkMusic_No_REST.audio_library.mixins
import SkylarkMusic_No_REST.audio_library.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0002_remove_track_genre_delete_genre_track_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=SkylarkMusic_No_REST.audio_library.mixins.get_path_upload_cover_track, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), SkylarkMusic_No_REST.audio_library.validators.validate_size_image]),
        ),
    ]
