# Generated by Django 4.2.11 on 2024-04-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0003_alter_track_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='license_tracks', to='audio_library.license'),
        ),
    ]
